package com.example.hackatonprjoect.common.model.fids
data class FidsEntity(
    var uid: String,
    var type: String? = null,
    var flightNumber: String? = null,
    var airlineCode: String? = null,
    var aircraft: String? = null,
    var destinationCode: String? = null,
    var originCode: String? = null,
    var scheduledTime: String? = null,
    var estimateTime: String? = null,
    var Codeshare: String? = null,
    var SharedFlightNumber: String? = null,
    var Stand: String? = null,
    var viaCode: String? = null,
    var gateNoGeneral: String? = null,
    var gateNoPremium: String? = null,
    var gateOpenGeneral: String? = null,
    var gateOpenPremium: String? = null,
    var gateCloseGeneral: String? = null,
    var gateClosePremium: String? = null,
    var actualTimeOfDep: String? = null,
    var BaggageBelt: String? = null,
    var airlineLogo: String? = null,
    var statusCode: String? = null,
    var destinationImage: String? = null,
    var checkInCounter: String? = null,
    var checkInCounterDisplay: String? = null,

//English
    var flightStatusEn: String? = null,
    var originNameEn: String? = null,
    var originCityEn: String? = null,
    var originCountryEn: String? = null,
    var destinationNameEn: String? = null,
    var destinationCityEn: String? = null,
    var destinationCountryEn: String? = null,
    var viaNameEn: String? = null,
    var viaCityEn: String? = null,
    var viaCountryEn: String? = null,
    var airlineNameEn: String? = null,

    //Arabic
    var flightStatusAr: String? = null,
    var originNameAr: String? = null,
    var originCityAr: String? = null,
    var originCountryAr: String? = null,
    var destinationNameAr: String? = null,
    var destinationCityAr: String? = null,
    var destinationCountryAr: String? = null,
    var viaNameAr: String? = null,
    var viaCityAr: String? = null,
    var viaCountryAr: String? = null,
    var airlineNameAr: String? = null,
    var locationId: String? = null,


) {
    // You can add a default constructor or an empty constructor
    constructor() : this(
        uid = "",
        type = null,
        flightNumber = null,
        airlineCode = null,
        destinationCode = null,
        originCode = null,
        scheduledTime = null,
        estimateTime = null,
        Codeshare = null,
        SharedFlightNumber = null,
        Stand = null,
        gateNoGeneral = null,
        gateNoPremium = null,
        gateOpenGeneral = null,
        gateOpenPremium = null,
        gateCloseGeneral = null,
        gateClosePremium = null,
        actualTimeOfDep = null,
        BaggageBelt = null,
        airlineLogo = null,
        statusCode = null,
        flightStatusEn = null,
        originNameEn = null,
        originCityEn = null,
        originCountryEn = null,
        destinationNameEn = null,
        destinationCityEn = null,
        destinationCountryEn = null,
        viaNameEn = null,
        viaCityEn = null,
        viaCountryEn = null,
        airlineNameEn = null,
        flightStatusAr = null,
        originNameAr = null,
        originCityAr = null,
        originCountryAr = null,
        destinationNameAr = null,
        destinationCityAr = null,
        destinationCountryAr = null,
        viaNameAr = null,
        viaCityAr = null,
        viaCountryAr = null,
        airlineNameAr = null,
        locationId = null,
    )
}

